
//初始化
export const INIT = "INIT"


//改变过滤器的值
export const CHANGE_ROW_FILTER = "CHANGE_ROW_FILTER"
export const CHANGE_COLUMN_FILTER = "CHANGE_COLUMN_FILTER"
export const CHANGE_SERVER_FILTER = "CHANGE_SERVER_FILTER"

//改变排序状态
export const CHANGE_SORT_DESC = "CHANGE_SORT_DESC"
export const CHANGE_SORT_COLUMN_ID = "CHANGE_SORT_COLUMN_ID"

//表格按钮状态
export const CHANGE_PAGE_INDEX = "CHANGE_PAGE_INDEX"
export const START_LOADING = "START_LOADING"
export const END_LOADING = "END_LOADING"
export const CHANGE_ROW_PER_PAGE = "CHANGE_ROW_PER_PAGE"

//设置表格数据
export const SET_SOURCE_DATA = "SET_SOURCE_DATA"
export const SET_COMPONENT_FILTER_DATA = "SET_COMPONENT_FILTER_DATA"
export const SET_INPUT_FILTER_DATA = "SET_INPUT_FILTER_DATA"
export const SET_SORTED_DATA = "SET_SORTED_DATA"
export const SET_DISPLAY_DATA = "SET_DISPLAY_DATA"

export const RESET_TABLE = "RESET_TABLE"
