import request from "../utils/request"

export const INIT = "INIT"
export const CHANGE_ROW_FILTER = "CHANGE_ROW_FILTER"
export const CHANGE_COLUMN_FILTER = "CHANGE_COLUMN_FILTER"
export const CHANGE_PAGE_INDEX = "CHANGE_PAGE_INDEX"
export const READ_START = "READ_START"
export const READ_SUCCESS = "READ_SUCCESS"
export const READ_FAILURE = "READ_FAILURE"
export const START_LOADING = "START_LOADING"
export const END_LOADING = "END_LOADING"
export const UPDATE_UI = "UPDATE_UI"

//设置表格数据
export const SET_SOURCE_DATA = "SET_SOURCE_DATA"
export const SET_COMPONENT_FILTER_DATA = "SET_COMPONENT_FILTER_DATA"
export const SET_INPUT_FILTER_DATA = "SET_INPUT_FILTER_DATA"
export const SET_SORTED_DATA = "SET_SORTED_DATA"
export const SET_DISPLAY_DATA = "SET_DISPLAY_DATA"

export const RESET_TABLE = "RESET_TABLE"
