export const SET_HEIGHT = "SET_HEIGHT"
export const CHANGE_GAME = "CHANGE_GAME"
export const TOGGLE_MENU = "TOGGLE_MENU"
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB"
export const SET_ITEM_LIST = "SET_ITEM_LIST"
export const ADD_ITEM = "ADD_ITEM"
export const CHANGE_ITEM = "CHANGE_ITEM"