export const SET_HEIGHT = "SET_HEIGHT"
export const CHANGE_GAME = "CHANGE_GAME"
export const TOGGLE_MENU = "TOGGLE_MENU"
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB"
export const SET_ITEM_LIST = "SET_ITEM_LIST"
export const SET_ITEM_BUNDLE_LIST = "SET_ITEM_BUNDLE_LIST"
export const SET_CHANNEL_LIST = "SET_CHANNEL_LIST"
export const ADD_ITEM = "ADD_ITEM"
export const CHANGE_ITEM = "CHANGE_ITEM"

export const SET_ITEM_BUNDLE_CREATE_START_TIME = "SET_ITEM_BUNDLE_CREATE_START_TIME"
export const SET_ITEM_BUNDLE_CREATE_END_TIME = "SET_ITEM_BUNDLE_CREATE_END_TIME"

export const SHOW_TIPS = "SHOW_TIPS"